name: DEVOPS_1

on:
  push:
    branches:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v1
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credential@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-access-key-key: ${{ secrets.AWS_ACCESS_KEY_KEY }}
      - name: Deploy static site to s3 bucket
        run: aws s3 sync . s3://devops-1-meme-genarator --delete
